linxu-t20: hdmi: Fix build error due to unusued variables
drivers/video/tegra/dc/hdmi.c: In function
'tegra_dc_hdmi_valid_asp_ratio':
drivers/video/tegra/dc/hdmi.c:1259:6: error: unused variable
's_aspratio' [-Werror=unused-variable]
drivers/video/tegra/dc/hdmi.c:1258:6: error: unused variable
'm_aspratio' [-Werror=unused-variable]
drivers/video/tegra/dc/hdmi.c:1257:6: error: unused variable 'count'
[-Werror=unused-variable]
drivers/video/tegra/dc/hdmi.c: At top level:
drivers/video/tegra/dc/hdmi.c:77:12: error:
'tegra_dc_hdmi_aspect_ratios' defined but not used [-Werror=unused-
variable]
cc1: all warnings being treated as errors
make[4]: *** [drivers/video/tegra/dc/hdmi.o] Error 1
make[3]: *** [drivers/video/tegra/dc] Error 2
make[2]: *** [drivers/video/tegra] Error 2
make[1]: *** [drivers/video] Error 2